accounts/urls.py
from django.urls import path

from .views import SignUpView, LogoutView, LoginView

app_name = 'accounts'

urlpatterns = [
    path("signup/", SignUpView.as_view(), name="signup"),
    path("login/", LoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
    path('', include('todo.urls'))
]

todo/urls.py
from django.urls import path
from . import views

app_name = 'todo'

urlpatterns = [
    path('', views.TodoList.as_view(), name='list'),
    path('create', views.TodoCreate.as_view(), name='create'),
    path('<int:pk>/edit/', views.TodoEdit.as_view(), name='edit'),
    path('<int:pk>/delete/', views.TodoDelete.as_view(), name='delete'),
]

accounts/models.py
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin
from django.db import models
from django.utils import timezone
from django.utils.translation import gettext_lazy as _

from .managers import CustomUserManager


class CustomUser(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(_("email address"), unique=True)
    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    date_joined = models.DateTimeField(default=timezone.now)

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    objects = CustomUserManager()

    def __str__(self):
        return self.email

todo/models.py
from django.db import models
from django.contrib.auth import get_user_model
import datetime

time = datetime.datetime.now(datetime.timezone.utc).astimezone().now()

user = get_user_model()

class Task(models.Model):
    user = models.ForeignKey(user, on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    STATUS_CHOICES = [
        ('Done', 'Done'),
        ('Not yet', 'Not yet'),
    ]
    status = models.CharField(
        max_length=7, choices=STATUS_CHOICES, default='Not yet')
    created_date = models.DateTimeField(default=time)
    due_date = models.DateField(null=True, help_text='yyyy-mm-dd')

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['-created_date']

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

from .models import CustomUser


class CustomUserCreationForm(UserCreationForm):

    class Meta:
        model = CustomUser
        fields = ("email",)


class CustomUserChangeForm(UserChangeForm):

    class Meta:
        model = CustomUser
        fields = ("email",)

accounts/views.py
from django.views.generic import CreateView
from django.contrib.auth.views import LogoutView as BaseLogoutView
from django.contrib.auth.views import LoginView as BaseLoginView
from django.urls import reverse_lazy

from .forms import CustomUserCreationForm

class LoginView(BaseLoginView):
    template_name = "registration/login.html"
    success_url = reverse_lazy('todo:list')
      
class SignUpView(CreateView):
    form_class = CustomUserCreationForm
    template_name = "registration/signup.html"
    success_url = reverse_lazy('todo:list')
    
class LogoutView(BaseLogoutView):
    template_name = "registration/logout.html"
    success_url = reverse_lazy('todo:list')

todo/views.py
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from .models import Task
from accounts.models import CustomUser


class TodoList(LoginRequiredMixin, ListView):
    context_object_name = 'tasks'

    def get_queryset(self):
        task = Task.objects.filter(user=self.request.user)
        return task

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        user = CustomUser.objects.get(email=self.request.user)
        email = str(user.email)
        x = email.find('@')
        data['username'] = email[:x]
        return data

class TodoCreate(LoginRequiredMixin, CreateView):
    model = Task
    fields = ['name', 'due_date']
    success_url = reverse_lazy('todo:list')
    template_name = 'todo/task_create.html'

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


class TodoEdit(LoginRequiredMixin, UpdateView):
    model = Task
    fields = ['name', 'status', 'due_date']
    success_url = reverse_lazy('todo:list')


class TodoDelete(LoginRequiredMixin, DeleteView):
    model = Task
    success_url = reverse_lazy('todo:list')

templates/todo/task_confirm_delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ToDo</title>
</head>
<body>
    <form method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    {{ form }}
    <input type="submit" value="Confirm">
</form>
</body>
</html>

templates/todo/task_create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ToDo</title>
</head>
<body>
    <form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Create">
</form>
</body>
</html>

templates/todo/task_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ToDo</title>
</head>
<body>
    <form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Confirm"> <button><a href="{% url 'todo:delete' pk=task.id %}">Delete</a></button>
</form>
</body>
</html>

templates/todo/task_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ToDo</title>
    <style>
      table {
        border-collapse: collapse;
        font-family: arial, sans-serif;
         width: 100%;
      }

      td, th {
      border: 1px solid #dddddd;
      padding: 8px;
      text-align: left;
      }

      tr:nth-child(even) {
      background-color: #dddddd;
      }
</style>
</head>
<body>
    <h1>ToDo</h1>
    <h4>Welcome {{username}}</h4> <h5><a href="{% url 'accounts:logout' %}">Log-out</a></h5>
    <a href="{% url 'todo:create' %}">Create</a> a new task!
    <table>
      <hr>
    <tr>
      <th>Task</th>
      <th>Status</th>
      <th>Created date</th>
      <th>Due date</th>
    </tr>
    {% for task in tasks %}
    <tr>
      <td><a href="{% url 'todo:edit' pk=task.id %}">{{task.name}}</a></td>
      <td>{{task.status}}</td>
      <td>{{task.created_date}}</td>
      <td>{{task.due_date}}</td>
    </tr>
    {% endfor %}
    </table>
    <hr>
    Contact : saeedroostaei79@gmail.com
</body>
</html>